services:
  local-db:
    image: postgres:16
    restart: always
    env_file:
      - env/.env.local
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
