name: main NestJS boilerplate
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  build:
    name: Test and Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          corepack enable pnpm
          corepack prepare
          pnpm --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'pnpm'

      - name: Get Node version
        id: node-version
        run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Cache CI files
        id: ci-cache
        uses: actions/cache@v4
        with:
          path: .cicache
          key: ${{ runner.os }}-ci-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ci-

      - name: Check package.json
        run: |
          echo Checking if package.json is normalized by installing and removing a new package
          pnpm i --loglevel warn --ignore-scripts dedupe@4.0.1
          pnpm rm --loglevel warn dedupe
          git diff --exit-code package.json pnpm-lock.yaml || (echo Your package.json or pnpm-lock.yaml file is not normalize. Did you add a package manually without pnpm ? && exit 1)

      - name: Test
        run: |
          pnpm tsc
          pnpm lint --cache --cache-strategy content --cache-location .cicache/eslint/.cache.json
          pnpm test:cov --cacheDirectory .cicache/jest

      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.2.21
        continue-on-error: true
        with:
          github-token: ${{ github.token }}

      - name: Cache Build files
        id: build-cache
        uses: actions/cache@v4
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: |
          pnpm build
